### ISSUE TITLE
Log when a task fail seems to loose underlyng exception (using logback and gelf)

### ISSUE THREAD

**Issue by Ouriel** [infiniticio/infinitic#103]
I have a task throwing an exception but my log in kibana don't show the stacktrace, just this log:
```taskId 1ce1d6d7-8d43-4cda-a3b7-0e49566e765c - error {}```
the additional `{}` seems weird and the stacktrace may be lost du to newline or not being attach?

**Comment by geomagilles** [comment]
this should be fixed now - I close the issue. Please reopen it if you still have the issue with 0.7.4+
