### ISSUE TITLE
Example with database or other stateful components

### ISSUE THREAD

**Issue by jeffzoch** [infiniticio/infinitic#115]
Hello,
Just been reading through the docs and am really interested in the project. One question I have is how a task should be passed a reference to something stateful like a database connection - the docs mentioned that both tasks and workers must have a zero-argument constructor and that parameters are serializable. Is there a way to pass in a db connection so that tasks can execute queries? 

Also wondering how to indicate a particular task's state should be recomputed each time - for example, if I have a task that reaches out to 5 hosts and finds 3 healthy ones I might want to, in the face of failures, recompute the list of healthy agents. Is there a mechanism I'm missing for doing this?

**Comment by geomagilles** [comment]
@jeffzoch Hi!

Thx for your comments. You can describe your datasource in a static variable. Please note that usually connection should be acquired and released within the non-static method, see https://stackoverflow.com/questions/9428573 .

Static states will be shared among task instances within a worker. Of course, different workers will have different static states.

I'm not sure to understand your last question. Can you elaborate?

**Comment by geomagilles** [comment]
@jeffzoch closing as there is no more activity
