### ISSUE TITLE
JVM target for the library could be bump higher 

### ISSUE THREAD

**Issue by Ouriel** [infiniticio/infinitic#124]
Today the compilation target is Java 1.8 maybe you could target higher version with Jave 11 being the last LTS and 16 out since few month.

**Comment by geomagilles** [comment]
The compilation target is 1.8 because some code should end up in Pulsar functions that support only 1.8. 
I remember that some recent improvement in the Pulsar codebase made it compatible with the higher java version - but it has to be confirmed.

**Comment by geomagilles** [comment]
use Java 11 since 0.9.5
