### ISSUE TITLE
Publish lifecycle events of workflow and task to a particular topic

### ISSUE THREAD

**Issue by Ouriel** [infiniticio/infinitic#129]
To be able to store and use the differents events for analytics purpose,
it will be great if the a subset of start, completion, cancellation or failure of workflow and task in a specific topic.
Use-case:
 - build analytics dashboard relative to lifecycle of task and workflow using tags or metadata.

**Comment by geomagilles** [comment]
Note: currently there are no events such as `TaskCompleted`, `TaskCanceled`, dWorkflowCompleted`, `WorkflowCanceled`(it's not needed by the engine). Providing those events will be useful for analytics purposes when introspecting the topics. Btw the dashboard will need them also

**Comment by geomagilles** [comment]
Completed with 0.13.0
