### ISSUE TITLE
Question: How are stateful functions made resilient?

### ISSUE THREAD

**Issue by phxnsharp** [infiniticio/infinitic#142]
Hello! Looks like a great project and I have a question I didn't find an answer for in your documentation. Your release of 0.80 supposes a start function as such:
``` Java
@Override public void start() {
  Instant now = inline(Instant::now);

  int w = 0;
  while (w < 56) {
    w++;
    timer(now.plusSeconds(w * weekInSeconds)).await();
    points++;
  }
}
```

If the computer hosting the worker running this workflow function were to crash, how would the state of this function be recovered? In particular, how would `w` be restored to where it was before the crash?

**Comment by geomagilles** [comment]
@phxnsharp thanks for your comment. The answer is yes, `w` would be restored in case of a crash. The point of Infinitic is to provide an easy, but reliable way, to code workflow. Documentation should be improved to better describe how it works - but you can have an introduction here https://gillesbarbier.medium.com/under-the-hood-of-a-workflow-as-code-event-driven-engine-6107dab9b87c
