### ISSUE TITLE
Singleton Service

### ISSUE THREAD

**Issue by gmendoza-wenance** [infiniticio/infinitic#167]
Hi! I need to know if it's possible execute a Workflow as a Singleton. I mean: I need the execution of only one workflow at any time.

**behavior expected**: when I call multiple dispatch calls, only execute the one, the others must die or throw a runtime error.

![Screenshot from 2022-08-11 11-08-15](https://user-images.githubusercontent.com/100857986/184152931-26212f84-2cec-4950-809b-cedc30fd538e.png)

If this is not possible, ¿May I implement another strategy? Maybe checkout if Infinitic is already running a SingletonWorkflow.class?

Thanks in advance

**Comment by gmendoza-wenance** [comment]
Maybe something like this helps
```
if (client.getRunningWorkflows().contains("singleton-workflow-id")) {
    System.out.println("Please wait...the singleton is working yet");
}
```

**Comment by Ouriel** [comment]
Hello,
I think you can achieve that with unique-tag. https://infinitic.substack.com/i/52382438/unique-tag
The feature isn't documented well at the moment but it works well.
Regards

**Comment by gmendoza-wenance** [comment]
Thanks Ouriel! It's correct, Gilles Barbier answered the the same in his Medium personal page. 
Regards!
