### ISSUE TITLE
Dependency injection for task generation

### ISSUE THREAD

**Issue by gmendoza-wenance** [infiniticio/infinitic#168]
Hi, I'm trying to develop a really simple (dummy) service to call to remote service using HTTP Client (Feign, WebClient or another)
The problem: I have an internal service class per environment so...how can I do to apply dependency injection in a Task?

I'm calling to `newTask(Service.class)` in my workflow.

Is setter injection in the task a good approach?
Thanks in advance

**Comment by geomagilles** [comment]
@gmendoza-wenance sorry for the delay - I missed the notification :( The workflow does not know the actual implementation of tasks - only their interface. There is few limitations about what you can do when writing tasks - see https://docs.infinitic.io/services/writing. Please provide some code examples, if this does not help you

**Comment by gmendoza-wenance** [comment]
Well, my actual scenario consist in a strategy service (Task) who may send a request to an external system depending of the environment. Using Spring Boot I have a config bean with different data per environment. This config bean must be setted as a field in Task implementation but Infinitic SDK provide the task creation through `newTask(Service.class)`.

I'll need a mechanism to inject my config by Constructor or setter via, of course respecting the limitations of Infinitic:
> A service is a Java/Kotlin class that:
> - must extend io.infinitic.tasks.Task abstract class
> - must have an empty constructor
> - have [serializable](https://docs.infinitic.io/references/serializability) methods parameters and return value
> - must be thread-safe

Example
```java
import io.infinitic.tasks.Task;

public class HelloWorldServiceImpl extends Task implements HelloWorldService {
    private final ConfigBean config;

    public HelloWorldServiceImpl() {}
    public HelloWorldServiceImpl(ConfigBean aConfig) {
         this.config = aConfig;
    }
 
    @Override
    public String sayHello(String name) {

        return "Hello " + ((name == null) ? "World" : this.config.transform(name));
    }

    @Override
    public String addEnthusiasm(String str) {

        return str + "!";
    }
}
......
HelloWorldService myService = infinitic.newTask(Service.class); // I need inject my config
```

Thanks in advance

**Comment by geomagilles** [comment]
@gmendoza-wenance 

In workflows, tasks are not instantiated by `newTask` - this function only creates a stub that - when used - will trigger a remote call to the [Service Worker](https://docs.infinitic.io/services/workers). 

So I believe what your need is a way to provide a custom instantiation in service workers - currently, instantiations are only possible through config files such as:
```yml
tasks:
  - name: example.booking.tasks.carRental.CarRentalService
    class: example.booking.tasks.carRental.CarRentalServiceFake
    concurrency: 5
```
Would this solve your issue? If yes, I will quickly update the workers to allow such custom instantiation.

**Comment by geomagilles** [comment]
@gmendoza-wenance the 0.10.0 release introduced a new way to register Service that allows you to have dependency injection (see bottom of https://docs.infinitic.io/services/workers/). Let me know if it solves your issue
