### ISSUE TITLE
"Commons Clause" License Condition clarification

### ISSUE THREAD

**Issue by greenbird-chr** [infiniticio/infinitic#176]
Hi. This looks like a very interesting project.

I was wondering if you could clarify the projects position reg. this vague formulation from the Commons Clause part of the license:

```a product or service whose value derives, entirely or substantially, from the functionality of the Software```

Are you following the definition from the "What does 'substantially' mean?" question in the [Commons Clause FAQ](https://commonsclause.com/)? E.g. if another project was to use Infinitic as a backend, and sell services on top of that, exposing different APIs and abstractions, that wold not be a breach of the license?

Regards
Christian

**Comment by geomagilles** [comment]
Hi @greenbird-chr, and thanks for the comment.

The objective of this license is to prevent from productizing Infinitic itself. It does not prevent a SaaS provider from using it to build a service based on it. For example, a marketing company uses it in production to run its marketing automation engine.

**Comment by greenbird-chr** [comment]
That's what I thought. Thanks for the quick answer.
