### ISSUE TITLE
Line separators prevent Infinitic from running on Windows Machines

### ISSUE THREAD

**Issue by mhays118** [infiniticio/infinitic#184]
One of my coworkers is running into a problem with this, based on the line separators on windows.

Windows uses the line separator `CR LF` for files, which is not the same as the `LF` separator used in Unix based systems like Linux and macOS.

When trying to use this on a windows machine, the Avro `/versions` file has already been created using the Unix system line endings `LF` (`\n`) in:
https://github.com/infiniticio/infinitic/blob/1a4a24abf58d5a265b63abeebefde6ee57b09c74/infinitic-common/build.gradle.kts#L59

But running this on windows, the compiled code will try using the Windows line endings:
https://github.com/infiniticio/infinitic/blob/1a4a24abf58d5a265b63abeebefde6ee57b09c74/infinitic-common/src/main/kotlin/io/infinitic/version.kt#L32

This will lead to the list of versions actually being one long string, where it is basically this:
```
versions = 0.9.0\n0.9.1\n0.9.2\n0.9.3\n0.9.4\n0.9.5\n0.9.6\n0.9.7\n0.9.8\n0.9.9\n0.9.10\n0.9.11\n0.9.12\n0.9.13\n0.10.0\n0.11.0\n0.11.1\n0.11.2\n0.11.3\n0.11.4
```

Which will cause this part of the code to fail:
https://github.com/infiniticio/infinitic/blob/1a4a24abf58d5a265b63abeebefde6ee57b09c74/infinitic-common/src/main/kotlin/io/infinitic/common/serDe/avro/AvroSerDe.kt#L143-L146C39
```kotlin
    return versions
        .filter { it.isNotEmpty() }
        .associateWith { version ->
          val url = "/$SCHEMAS_FOLDER/$prefix-$version.avsc"
```
As this is not a vaild file:
```
$prefix-0.9.0\n0.9.1\n0.9.2\n0.9.3\n0.9.4\n0.9.5\n0.9.6\n0.9.7\n0.9.8\n0.9.9\n0.9.10\n0.9.11\n0.9.12\n0.9.13\n0.10.0\n0.11.0\n0.11.1\n0.11.2\n0.11.3\n0.11.4.avsc
```

**Comment by geomagilles** [comment]
@mhays118 sorry, I somehow missed the notification. Is that something you can try to fix? It does not appear complex, but I do not have a windows machine with me. If not, I can try, but I will need you to test before releasing a fix.
