### ISSUE TITLE
Spring Boot Integration - Review Request

### ISSUE THREAD

**Issue by tiarebalbi** [infiniticio/infinitic#190]
Hi,

I'm integrating infinitic in a Spring Boot Project and I would like to get the feedback from the creators :) 

The idea is to simplify the process to load the configuration and automatically initialise the sub-processes like the Worker initialization. This will also register the client, if needed.

https://github.com/tiarebalbi/infinitic-spring-boot-integration 

Right now I have this project under my account, but I would be happy to transfer it over and keep contributing on top of it.

The installation would work like:
**Installation:** Add the Infinitic dependency to your pom.xml or build.gradle file.

```xml
<!-- Example for Maven -->
<dependency>
    <groupId>com.tiarebalbi.infinitic</groupId>
    <artifactId>infinitic-spring-boot-3-starter</artifactId>
    <version>[version]</version>
</dependency>
```

**Configuration:** Configure the Infinitic integration in your Spring Boot application's configuration files.

```properties

# Enable auto-configure
infinitic.enabled=true
## Worker Setting
infinitic.worker.enabled=true
infinitic.worker.configuration=classpath:infinitic-worker.yml
## Client Setting
infinitic.client.enabled=true
infinitic.client.configuration=classpath:infinitic-client.yml
```

**Usage:** Start using the Infinitic library in your application code.

```kotlin
@Service
class InfiniticDemoService {

    @Autowired
    private lateinit var infiniticClient: InfiniticClient

    fun runProcess() {
        val event = this.infiniticClient.newWorkflow(AnnotatedWorkflow::class.java)
        val result = event.concatABC("Demo-")
        println(result)
    }
}
```

**Comment by geomagilles** [comment]
Thx @tiarebalbi - sorry for the late response, and thx for asking. I'll look at it next week

**Comment by geomagilles** [comment]
@tiarebalbi Thanks for the proposal - I'm not willing to include this in the main repo - I'm not sure yet if it makes sense to include integrations - but I'd like to cite and link it from the documentation - Is that ok with you?

**Comment by tiarebalbi** [comment]
Thanks for taking the time @geomagilles , yep that sounds good.
