### ISSUE TITLE
Question: Infinitic InMemory Support

### ISSUE THREAD

**Issue by tiarebalbi** [infiniticio/infinitic#215]
Hi there, I have been using the infinitic-inMemory for my integration tests. Is the plan to still support this package? I just updated my code to use the `0.12.3` and I noticed the latest build for the infinitic-inMemory was the `0.11.7`.

https://central.sonatype.com/artifact/io.infinitic/infinitic-inMemory/0.11.7

**Comment by geomagilles** [comment]
Hi, thx for the heads up. The in memory implementation is also used for Infinitic development. I’ll check what happened but make sure to include it in the coming 0.13.0 version

**Comment by geomagilles** [comment]
@tiarebalbi since 0.12.0, the repository has changed its name to [infinitic-transport-inMemory](https://mvnrepository.com/artifact/io.infinitic/infinitic-transport-inMemory/0.12.3). I'll close this issue.

**Comment by tiarebalbi** [comment]
Perfect! Thanks
