### ISSUE TITLE
Add parameter for prefix infinitc table in db storage 

### ISSUE THREAD

**Issue by nseb** [infiniticio/infinitic#233]
HI
As part of our project we want to use a single db, in order to keep clarity in our schema, we would like to have a parameter to prefix the tables used by infinitic.

**Comment by geomagilles** [comment]
@nseb what is the purpose of this prefix? How do you expect to use or configure it?

**Comment by nseb** [comment]
@geomagilles 
My microservice already uses a database, the need is that for infinitic which will be used by this existing microservice, I can use the same storage
Firstly, ideally I would like to be able to inject the configuration of the datasource (spring bean of the configuration of my datasource) to have only one declaration.
As it is the same datasource, I would like the tables created/used by infinitic to be prefixed with a name (that I can configure) in order to find them easily and not keep my db schema readable.

**Comment by geomagilles** [comment]
Fixed in 0.14.1 that gives the ability to name the tables. The injection of the conjuration through Spring should be done separately
