### ISSUE TITLE
Register a workflow with a factory/bean , as we can do for a service

### ISSUE THREAD

**Issue by nseb** [infiniticio/infinitic#244]
Like registering a service I would like to be able to register a workflow with factory/bean with my spring context.

`
Autowired
private MyServiceFactory myServiceFactory; 
...

 infiniticWorker.registerWorkflowExecutor(MyService.class.getName() ,  () -> myServiceFactory.getObject()....);
`

**Comment by geomagilles** [comment]
Note that due to the workflow versioning system (cf. https://docs.infinitic.io/docs/workflows/versioning#new-workflows), we should have also a method with a list of 

infiniticWorker.registerWorkflowExecutor(workflowName , List.of(
() -> Workflow,
() -> Workflow,
() -> Workflow,
),  ....);

**Comment by geomagilles** [comment]
Fixed by 54d3e8ee60aff3e8a0fcfda3dbef848c1ed316e5
