### ISSUE TITLE
How to run multiple same tasks parallely

### ISSUE THREAD

**Issue by ManokarG** [infiniticio/infinitic#87]
How to run multiple same tasks parallely and wait for all of them to complete and return the result from workflow.

Like having a Deferred.awaitAll([Tasks....])

**Comment by geomagilles** [comment]
Hi, 

Yes, you can: the feature exists but is not documented because I'm still looking for the right syntax in Java. Are you on Java or Kotlin?

When you have 2 Deferred d1, d2 in a workflow, in Kotlin, you can do:
(d1 or d2).await()
(d1 and d2).await()
or any logical combination, actually.

**Comment by ManokarG** [comment]
Thanks for the update @geomagilles , I have tried to do what you've said, But i got the below error in type.

```
override fun getAll(): GetAllResult {
        val userResult = async {
            getUserTask.getUser()
        }.await()
        inline {
            println("User data received")
        }
        val userResultWithPosts = userResult.user.map {
            inline {
                println("Getting posts for " + it.id)
            }
            val posts = async {
                getPostTask.getPost(it.id!!)
            }
            return@map posts
        }
        val users = async { }.or(userResultWithPosts).await()
        inline {
            println("Received All posts")
        }
        return GetAllResult(users)
    }

```
Here in the line `async {}.or(userResultWithPosts).await()` I am getting the below error,
I needed to resolve the List<Deferred<T>>

Let me know the proper way.

**```
Type mismatch.
Required:
Deferred<List<TypeVariable(T)>>
Found:
List<Deferred<GetPostResult>>
```**

**Comment by ManokarG** [comment]
@geomagilles I found the proper code syntax now it's working fine, I am able to call the multiple tasks parallely and wait for all of them to finish.

Pasting the code for future ref

```
val userResultWithPosts = userResult.user.map {
            inline {
                println("Getting posts for " + it.id)
            }
            val posts = async {
                val data = async{
                    getPostTask.getPost(it.id!!)
                }.await()
                it.posts = data.post
                return@async it
            }
            return@map posts
        }.and().await()
```

**Comment by geomagilles** [comment]
@ManokarG ok. Note that:
```
val data = async{
     getPostTask.getPost(it.id!!)
}.await()
```
should be replaced by
```
val data = getPostTask.getPost(it.id!!)
```
same for 
```
val userResult = async {
    getUserTask.getUser()
}.await()
```
with
```
val userResult = getUserTask.getUser()
```

**Comment by ManokarG** [comment]
@geomagilles My bad, Changed the code, everything works fine.
