### ISSUE TITLE
Update running workflow code

### ISSUE THREAD

**Issue by ManokarG** [infiniticio/infinitic#91]
Everytime i ran a workflow and need to do some changes in the workflow how can i cancel all the previous running workflows and start the new workflow with the latest code.

Currently it always showing workflow updated while running error, In docs i don't see we have any option to cancel the workflow and or update latest code for an existing workflow.

Consider providing more code samples as this help in time for new people trying out this new workflow engine.

**Comment by ManokarG** [comment]
Also when i faced an issue of WorkflowUpdated while running, i can't always run new workflow with the latest code

Instead i have to remove the docker volume and restart the docker to start a new instance, It is cumbersome to trying new features.

Is there any way how you are handling this ? I saw the docs i don't see much about this case.

**Comment by ManokarG** [comment]
Any update on this @geomagilles ? Did you able to understand this issue ?

**Comment by geomagilles** [comment]
@ManokarG Yes. #92 should fix your issue. Updating your workflow will trigger an error for previous workflows but should not prevent the execution of new ones. Please provide details if you think it's the case

**Comment by ManokarG** [comment]
Working as expected, but still the previous workflow execution exception log showing everytime i restart the worker.
